FootBall/urls.py
from django.urls import path
from FootBall import views

app_name = 'FootBall'

urlpatterns = [

    path("", views.Home, name="home"),
     
    #  for team buy 
    path('team-list/', views.team_list, name ="team_list"),
    path('teams/buy/<int:team_id>/', views.buy_team, name='buy_team'),

    # User dashboard 
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('purchased-team/', views.purchased_team_info_view, name='purchased_team_info'),
    path('invoice/<int:purchase_id>/', views.invoice_view, name='invoice_view'),
    path('update-team-user/<pk>/', views.UpdateTeam_user, name='update_team_user'),

    path('player-team/', views.player_team_info_view, name='player_team_info'),
    path('add-player-team/', views.add_player_team, name='add_player_team'),
    path('team-player-info/<int:player_id>/', views.team_playerinfo, name='team_player_info'),

    path('team-matche-info/', views.team_matche_info, name='team_matche_info'),

    path('team-report-user/', views.teamreport_user, name='team_report_user'),
    path('team-report-info-user/<int:team_id>/', views.team_report_info_view_user, name='team_report_info_user'),




    
    #  admin dashbord CRUD for team
    path('admin-dashboard/', views.admin_dashboard, name='admin_dash'),
    path('admin-team-list/', views.adminteam, name='admin_team'),
    path('add-team/', views.add_team, name='add_team'),
    path('update-team/<pk>/', views.UpdateTeam, name='update_team'),
    path('delete-team/<int:del_id>/', views.DeleteTeam, name='delete_team'),


    #  admin dashbord CRUD for player
    path('player-list/', views.Player_list.as_view(), name='player_list'),
    path('player-info/<int:player_id>/', views.playerinfo, name='player_info'),
    path('add-player/', views.add_player, name='add_player'),
    path('update-player/<pk>/', views.UpdatePlayer, name='update_player'),
    path('delete-player/<int:del_id>/', views.Deleteplayer, name='delete_player'),

    #  admin dashbord CRUD for Matches
    path('matches-list/', views.matchelist, name='matches_list'),
    path('create-matche/', views.create_match, name='create_matche'),
    path('update-matche/<pk>/', views.update_match.as_view(), name='update_matche'),


    #admin dashbord CURD for Refeere
    path('referee/',views.refeere, name='referee' ),
    path('add-refeere/', views.add_refeere, name='add_refeere'),
    path('update-refeere/<pk>/', views.UpdateReferee, name='update_refeere'),
    path('delete-refeere/<int:del_id>/', views.DeleteRefee, name='delete_refeere'),


    # admin dashboard CURD for News 
    path('news-list', views.newslist, name='news_list'),
    path('add-news/', views.add_News, name='add_news'),

    path('update-news/<pk>/', views.UpdateNews, name='update_news'),
    path('delete-news/<int:del_id>/', views.DeleteNews, name='delete_news'),


    # admin dashboard CURD for League
    path('league-list', views.leaguelist, name='league_list'),
    path('add-league/', views.add_league, name='add_league'),
    path('update-league/<pk>/', views.Updateleague, name='update_league'),
    path('delete-league/<int:del_id>/', views.Deleteleague, name='delete_league'),

    # admin dashboard CURD for team puchase  
    path('team-purchase/', views.teampurchase, name='team_purchase'),
    path('payment-details/', views.Paymentdetails, name='payment_details'),
    path('update-team-purchase/<pk>/', views.UpdateteamPur, name='update_team_purchase'),
    path('delete-team-purchase/<int:del_id>/', views.DeleteTeamPurchase, name='delete_team_purchase'),


    # admin dashboard CURD for team report 
    path('team-report/', views.teamreport, name='team_report'),
    path('team-report-info/<int:team_id>/', views.team_report_info_view, name='team_report_info'),



     # admin dashboard CURD for matche report 
    path('matche-report/', views.Matchereport, name='matche_report'),










   










   



    path('players/', views.players, name="players"),
    path('blogs/', views.blogs, name="blogs"),
    path('contact/', views.contact, name="contact"),
    path('single-players/', views.single_players, name="single_ply"),

    # for show live matches and information 
    path('live-matches/', views.livematch, name="live_matches"),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/',views.MatcheInfo,name='match_info'),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/', views.MatcheInfo, name='match_detail'),


   






]

ICFL/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("league/", include('FootBall.urls')),
    path("login/", include('Login.urls')),
    path("", views.index, name='index'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'Login'

urlpatterns = [

    path('signup/', views.sign_up, name='signup'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('profile/', views.profile, name='profile'),

    # path('change-profile/', views.user_change, name='user_change'),
    # path('update_password/', views.update_password, name='update_password'), 
    path('add_propic/', views.add_propic, name='add_propic'),  
    path('change_propic/', views.change_propic, name='change_propic'),     


]

Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name="users")
    pro_pic = models.ImageField(upload_to='profile_pics')
    

Login/forms.py
from django import forms
from .models import Profile


class ProfilePic(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['pro_pic']

Login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Login.forms import ProfilePic
# Create your views here.

def sign_up(request):
    registered =False
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        
        if pass1 != pass2:
            return HttpResponse("Password not same")
        data = User.objects.create_user(username,email,pass1)
        data.save()
        registered = True
            
    dict = {'registered': registered}
    return render(request, 'Login/signup.html', context=dict)



def Login(request):

    Login = False
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']

        user=authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
           Login = True
    dict = {'Login': Login}
    return render(request, 'Login/login.html', context=dict)


@login_required
def Logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request, 'Login/profile.html', context={})


# @login_required
# def user_change(request):
#     if request.method == "POST":
#         username = request.POST.get('username')
#         first_name = request.POST.get('first_name')
#         last_name = request.POST.get('last_name')
#         email = request.POST.get('email')
        
#         user = request.user
#         user.username = username
#         user.first_name = first_name
#         user.last_name = last_name
#         user.email = email
#         user.save()
#         return HttpResponseRedirect(reverse('App_login:profile'))
#     else:
#         return render(request, 'App_login/cngprofile.html', {'user': request.user})
        
    
# @login_required  
# def update_password(request):
#     current_user = request.user
#     changed = False
#     form = PasswordChangeForm(current_user)
#     if request.method =='POST':
#         form = PasswordChangeForm(current_user, data=request.POST)
#         if form.is_valid():
#             form.save()
#             changed = True

#     return render(request, 'App_login/changepass.html', context={'form':form, 'changed': changed})


@login_required
def add_propic(request):
    form = ProfilePic()
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user =request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('Login:profile'))
    return render(request, 'Login/pro_pic.html', context={'form': form})



@login_required
def change_propic(request):
    form = ProfilePic(instance = request.user.users)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance = request.user.users)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login:profile'))
    return render(request, 'Login/pro_pic.html',  {'form':form})

templates/Login/changepass.html
{% extends 'bases.html' %}

{% load crispy_forms_tags %}

{% block title_block %} Profile {% endblock %}
{% block content %}

{% if changed %}
<div class="alert alert-success">
    Password Change Successfully!
</div>
{% endif %}
<form  method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <br>

    <button type="submit" class="btn btn-warning btn-sm">Change Password</button>
    
</form>

{% endblock content %}

templates/Login/cngprofile.html
{% extends 'bases.html' %}
{% block title_block %} Profile {% endblock %}


{% block content %}

<form method="POST" class="signup">
   {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>

    <label for="firstname">First Name:</label>
    <input type="text" id="firstname" name="first_name" required>

    <label for="lastname">Last Name:</label>
    <input type="text" id="lastname" name="last_name" required>
    
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required> <br>

    <a href="{% url 'App_login:update_password' %}">Change Password</a>
    
    <input type="submit" value="Submit" class="btn btn-success">
</form>

{% endblock content %}

templates/Login/login.html
{% extends 'bases.html' %}
{% load static %}

{% block title %} ICFL Login {% endblock title %}


{% block main-content %}

<section class="signup">
    <div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-10 col-md-9 col-lg-7 col-xl-6">
                        <div class="card-body p-4">
                            <h2 class="text-uppercase text-center mb-5">LOGIN YOUR ACCOUNT</h2>

                            {% if Login %}
                            <div class="alert alert-success">
                                Username or Passowrd incorrect ! <a href="{% url 'Login:login' %}">Try Agian </a>
                            </div>
                            {% else %}

                            <form method="POST">
                                {% csrf_token %}

                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="text" name="username" d="form3Example3cg" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example1cg">User Name</label>
                                </div>
                                <!-- id="form3Example3cg"  id="username" -->


                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="password" id="psw" name="password" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example4cg">Password</label>
                                </div>


                                <div class="d-flex justify-content-center">
                                    <button data-mdb-button-init type="submit" value="Submit" data-mdb-ripple-init
                                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Login</button>
                                </div>

                                <p class="text-center text-white mt-5 mb-0">Create an Account! <a href="{% url 'Login:signup' %}"
                                        class="fw-bold text-body"><u>SignUp</u></a></p>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endif %}


{% endblock main-content %}

templates/Login/pro_pic.html
{% extends 'bases.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Add Profile Pic {% endblock title %}


{% block main-content %}


<div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">

    <div class="row d-flex  justify-content-center align-items-center h-100">

        <div class="col-md-7">
            <!-- card p-3 py-4  -->
            <div class="">
                <h5>Add Your Profile pic </h5>

                <form method="POST" enctype="multipart/form-data">
            
                   
                    {% csrf_token %}
                    {{ form | crispy }}

                
                    <button type="submit" class="btn btn-info btn-sm">Add Pic</button>
                </form>
            </div>
        </div>
    </div>

</div>


{% endblock main-content %}

templates/Login/profile.html
{% extends 'bases.html' %}
{% load static %}

{% block title %}  ICFL profile {% endblock title %}


{% block main-content %}

<div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">

    <div class="row d-flex  justify-content-center align-items-center h-100">

        <div class="col-md-7">
            <!-- card p-3 py-4 -->
            <div class="border text-center">

                <div class="text-center">
                    {% if user.users %}
                    <a href="{% url 'Login:change_propic' %}"> <img src="/media/{{user.users.pro_pic}}"
                            class="rounded-circle" width="100px" height="100px"> </a>

                    {% else %}

                    <a href="{% url 'Login:add_propic' %}"> <img src="{% static 'Images/logo.2.png' %}"
                            class="rounded-circle" width="100px"> </a>

                    {% endif %}

                    <span class="bg-secondary p-1 px-4 rounded text-white">Pro</span>
                    <h5 class="mt-2 mb-0 text-white">{{user.username}}</h5>
                    <span class="text-white">{{user.email}}</span>

                </div>

                <a href="{% url 'FootBall:team_list' %}" class="btn btn-outline-danger px-4">Join The League </a>

            </div>
        </div>
    </div>
</div>

{% endblock main-content %}

templates/Login/signup.html
{% extends 'bases.html' %}
{% load static %}

{% block title %} ICFL Signup {% endblock title %}


{% block main-content %}

<section class="signup">
    <div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-10 col-md-9 col-lg-7 col-xl-6">
                        <div class="card-body p-4">
                            <h2 class="text-uppercase text-center mt-5">Create an account</h2>
                            {% if registered %}
                            <div class="alert alert-success">
                                Account Created Successfully !
                            </div>

                            {% endif %}

                            <form method="POST">
                                {% csrf_token %}

                                <div data-mdb-input-init class="form-outline mb-3">
                                    <input type="text" id="username" name="username" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example1cg">User Name</label>
                                </div>
                                <!-- id="form3Example3cg" -->

                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="email" id="email" name="email" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example3cg">Your Email</label>
                                </div>

                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="password" id="password1" name="password1" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example4cg">Password</label>
                                </div>

                                <div data-mdb-input-init class="form-outline mb-4">
                                    <input type="password" id="password2" name="password2" required
                                        class="form-control form-control-lg" />
                                    <label class="form-label" for="form3Example4cdg">Repeat your password</label>
                                </div>

                                <div class="form-check d-flex justify-content-center mb-5">
                                    <input class="form-check-input me-2" type="checkbox" value=""
                                        id="form2Example3cg" />

                                    <label class="form-check-label text-white" for="form2Example3g">
                                        I agree all statements in <a href="#!" class="text-body">
                                            <u>Terms of service</u></a>
                                    </label>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button data-mdb-button-init type="submit" value="Submit" data-mdb-ripple-init
                                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                                </div>

                                <p class="text-center text-white mt-2 mb-0">Have already an account? <a
                                        href="{% url 'Login:login' %}" class="fw-bold text-body "><u>Login
                                            here</u></a></p>

                            </form>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br>



{% endblock main-content %}