FootBall/urls.py
from django.urls import path
from FootBall import views

app_name = 'FootBall'

urlpatterns = [

    path("", views.Home, name="home"),
     
    #  for team buy 
    path('team-list/', views.team_list, name ="team_list"),
    path('teams/buy/<int:team_id>/', views.buy_team, name='buy_team'),

    # User dashboard 
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('purchased-team/', views.purchased_team_info_view, name='purchased_team_info'),
    path('invoice/<int:purchase_id>/', views.invoice_view, name='invoice_view'),
    path('update-team-user/<pk>/', views.UpdateTeam_user, name='update_team_user'),

    path('player-team/', views.player_team_info_view, name='player_team_info'),
    path('add-player-team/', views.add_player_team, name='add_player_team'),
    path('team-player-info/<int:player_id>/', views.team_playerinfo, name='team_player_info'),

    path('team-matche-info/', views.team_matche_info, name='team_matche_info'),

    path('team-report-user/', views.teamreport_user, name='team_report_user'),
    path('team-report-info-user/<int:team_id>/', views.team_report_info_view_user, name='team_report_info_user'),




    
    #  admin dashbord CRUD for team
    path('admin-dashboard/', views.admin_dashboard, name='admin_dash'),
    path('admin-team-list/', views.adminteam, name='admin_team'),
    path('add-team/', views.add_team, name='add_team'),
    path('update-team/<pk>/', views.UpdateTeam, name='update_team'),
    path('delete-team/<int:del_id>/', views.DeleteTeam, name='delete_team'),


    #  admin dashbord CRUD for player
    path('player-list/', views.Player_list.as_view(), name='player_list'),
    path('player-info/<int:player_id>/', views.playerinfo, name='player_info'),
    path('add-player/', views.add_player, name='add_player'),
    path('update-player/<pk>/', views.UpdatePlayer, name='update_player'),
    path('delete-player/<int:del_id>/', views.Deleteplayer, name='delete_player'),

    #  admin dashbord CRUD for Matches
    path('matches-list/', views.matchelist, name='matches_list'),
    path('create-matche/', views.create_match, name='create_matche'),
    path('update-matche/<pk>/', views.update_match.as_view(), name='update_matche'),


    #admin dashbord CURD for Refeere
    path('referee/',views.refeere, name='referee' ),
    path('add-refeere/', views.add_refeere, name='add_refeere'),
    path('update-refeere/<pk>/', views.UpdateReferee, name='update_refeere'),
    path('delete-refeere/<int:del_id>/', views.DeleteRefee, name='delete_refeere'),


    # admin dashboard CURD for News 
    path('news-list', views.newslist, name='news_list'),
    path('add-news/', views.add_News, name='add_news'),

    path('update-news/<pk>/', views.UpdateNews, name='update_news'),
    path('delete-news/<int:del_id>/', views.DeleteNews, name='delete_news'),


    # admin dashboard CURD for League
    path('league-list', views.leaguelist, name='league_list'),
    path('add-league/', views.add_league, name='add_league'),
    path('update-league/<pk>/', views.Updateleague, name='update_league'),
    path('delete-league/<int:del_id>/', views.Deleteleague, name='delete_league'),

    # admin dashboard CURD for team puchase  
    path('team-purchase/', views.teampurchase, name='team_purchase'),
    path('payment-details/', views.Paymentdetails, name='payment_details'),
    path('update-team-purchase/<pk>/', views.UpdateteamPur, name='update_team_purchase'),
    path('delete-team-purchase/<int:del_id>/', views.DeleteTeamPurchase, name='delete_team_purchase'),


    # admin dashboard CURD for team report 
    path('team-report/', views.teamreport, name='team_report'),
    path('team-report-info/<int:team_id>/', views.team_report_info_view, name='team_report_info'),



     # admin dashboard CURD for matche report 
    path('matche-report/', views.Matchereport, name='matche_report'),










   










   



    path('players/', views.players, name="players"),
    path('blogs/', views.blogs, name="blogs"),
    path('contact/', views.contact, name="contact"),
    path('single-players/', views.single_players, name="single_ply"),

    # for show live matches and information 
    path('live-matches/', views.livematch, name="live_matches"),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/',views.MatcheInfo,name='match_info'),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/', views.MatcheInfo, name='match_detail'),


   






]

ICFL/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("league/", include('FootBall.urls')),
    path("login/", include('Login.urls')),
    path("", views.index, name='index'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FootBall/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

from django.db.models import Q
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Count, Sum
from django.db.models.signals import post_save, m2m_changed

# Create your models here.



BATCH_CHOICES = [
    ('201','201'),
    ('202', '202'),
    ('203', '203'),
    ('211', '211'),
    ('212', '212'),
    ('213', '213'),
    ('221', '221'),
    ('222', '222'),
    ('223', '223'),
    ('231', '231'),
    ('232', '232'),
    ('233', '233'),
    ('241', '241'),
    ('242', '242'),
]

POSITION_PLAY =[
    ('GK','Goalkeeper'),
    ('SW','Sweeper'),
    ('CB','Centre Back'),
    ('FB','Full Back'),
    ('WB','Wing Back'),
    ('DM','Defensive Midfielder'),
    ('CM','Centre Midfielder'),
    ('WM','Wing Midfielder'),
    ('AM','Attacking Midfielder'),
    ('WF','Wing Forward'),
    ('CF','Centre Forward'),

]
BLOOD_CHOICES = [
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),

]
GROUP_CHOICES =[
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E','E'),
]
FORM_CHOICES =[
    ('DRAW', 'D'),
    ('WIN', 'W'),
    ('LOST', 'L'),

]
TEAM_STATUS = [
    ('Panding', 'Panding'),
    ('Accepted', 'Accepted'),
    ('Rejected', 'Rejected'),

]


class Team(models.Model):
    team_name = models.CharField(max_length=30, verbose_name="team name")
    team_logo = models.ImageField(upload_to="team_logo", verbose_name="Team Logo")
    coach_name = models.CharField(max_length=20, verbose_name="Coach Name")
    batch_name = models.CharField(choices=BATCH_CHOICES, max_length=20)
    phone = models.CharField(max_length=20, verbose_name="Phone Number")
    email = models.EmailField(max_length=50, verbose_name="Team Email")
    price = models.DecimalField(max_digits=10, decimal_places=2)
   

    def __str__(self):
        return str(self.team_name)


class Player(models.Model):
    player_name = models.CharField(max_length=50, verbose_name="player name")
    image = models.ImageField(upload_to='player_images')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="plyers")
    player_uid = models.CharField(max_length=10, verbose_name="Player ID")
    batch = models.CharField(choices=BATCH_CHOICES, max_length=20, verbose_name="Select Batch ")
    player_jersey_no = models.SmallIntegerField(default=0,verbose_name="Player Jersey No")
    phone = models.CharField(max_length=20, verbose_name="Player Phone")
    email = models.EmailField(max_length=50, verbose_name="Player Email")
    blood_group = models.CharField(choices=BLOOD_CHOICES, max_length=20, verbose_name="Blood Group")
    age = models.CharField(max_length=10, verbose_name="Player Age")
    height = models.PositiveIntegerField(default=0, verbose_name="Player Height (cm)")
    weight = models.PositiveIntegerField(default=0, verbose_name="Player Weight (kg)")
    footed = models.CharField(max_length=50, verbose_name="Footed (Left or Right)")
    play_position = models.CharField(choices=POSITION_PLAY, max_length=50, verbose_name="Position Play")

    total_goals = models.PositiveIntegerField(default=0, blank=True, null=True, verbose_name="Total Goals")
    Total_assist = models.PositiveIntegerField(default=0, verbose_name="Total Goals Assists")
    total_matches = models.PositiveIntegerField(default=0, blank=True, null=True, verbose_name="Total Matches")
    yellow_cards = models.PositiveIntegerField(default=0, verbose_name="Yellow Cards")
    red_cards = models.PositiveIntegerField(default=0, verbose_name="Red Cards")
    totalplayer_of_match = models.PositiveIntegerField(default=0, verbose_name="Total Player of the Match")

    def __str__(self):
        return self.player_name



    
class Referee(models.Model):
    referee_name = models.CharField(max_length=50, verbose_name="Referee Name")
    referee_img = models.ImageField(upload_to='referee_images')
    phone = models.CharField(max_length=20, verbose_name="Phone Number")
    email = models.EmailField(max_length=50, verbose_name="Email")
    info = models.TextField()
    total_officiated = models.PositiveIntegerField(verbose_name="Total Matches Officiated")

    def __str__(self):
        return self.referee_name


class TeamStats(models.Model):
    team = models.OneToOneField(Team, on_delete=models.CASCADE, related_name="stats")
    matches_played = models.PositiveIntegerField(default=0)
    wins = models.PositiveIntegerField(default=0)
    draws = models.PositiveIntegerField(default=0)
    losses = models.PositiveIntegerField(default=0)
    goals_scored = models.PositiveIntegerField(default=0)
    goals_conceded = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)


    @property
    def win_percentage(self):
        if self.matches_played > 0:
            return (self.wins / self.matches_played) * 100
        return 0
    
    @property
    def loss_percentage(self):
        if self.matches_played > 0:
            return (self.losses / self.matches_played) * 100
        return 0
    
    @property
    def draws_percentage(self):
        if self.matches_played > 0:
            return (self.draws / self.matches_played) * 100
        return 0

    def __str__(self):
        return f"{self.team.name} Stats"





class Match(models.Model):
    left_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="left_matches")
    right_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="right_matches")
    left_score = models.PositiveIntegerField(default=0, verbose_name="Left Team Score")
    right_score = models.PositiveIntegerField(default=0, verbose_name="Right Team Score")

    scoring_players_left_team = models.ManyToManyField(Player, related_name="left_team_scoring_matches", blank=True)
    scoring_players_right_team = models.ManyToManyField(Player, related_name="right_team_scoring_matches", blank=True)
    Total_assist_left_team = models.ManyToManyField(Player, related_name="left_team_Total_assist", blank=True)
    Total_assist_right_team = models.ManyToManyField(Player, related_name="right_team_Total_assist", blank=True)

    yellow_card_players_left_team = models.ManyToManyField(Player, related_name="left_team_yellow_card_matches", blank=True)
    yellow_card_players_right_team = models.ManyToManyField(Player, related_name="right_team_yellow_card_matches", blank=True)
    red_card_players_left_team = models.ManyToManyField(Player, related_name="left_team_red_card_matches", blank=True)
    red_card_players_right_team = models.ManyToManyField(Player, related_name="right_team_red_card_matches", blank=True)
    player_of_match = models.ForeignKey(Player, related_name="player_of_match", on_delete=models.SET_NULL, null=True, blank=True)

    left_formation = models.CharField(max_length=10, verbose_name="Left Team Formation 4-3-3-1",blank=True,)
    right_formation = models.CharField(max_length=10, verbose_name="Right Team Formation 4-4-2-1",blank=True)
    referee = models.ForeignKey(Referee,  on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(verbose_name="Match Time", auto_now_add=False)
    match_details = models.TextField(verbose_name="Match Details",blank=True)
    location = models.CharField(max_length=100, verbose_name="Match Location")
    img = models.ImageField(upload_to='match_images', null=True, blank=True)
    highlights = models.FileField(
        upload_to='videos', null=True, blank=True,
        validators=[FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]
    )
    live = models.BooleanField(default=True)
     
    # class Meta:
    #     ordering = ('create_at',)

  
    def __str__(self):
        return "{} vs {}".format(self.left_team.team_name, self.right_team.team_name)
    



    @property
    def get_left_team_name(self):
        return "".format(self.left_team.team_name)
    
    @property
    def get_right_team_name(self):
        return "".format(self.right_team.team_name)






EVENT_CHOICES = [
       ('start', 'start'),
        ('goal','goal'),
        ('corner', 'corner'),
        ('foul', 'foul'),
        ('penalty', 'penalty'),
        ('offside','offside'),
        ('red', 'red card'),
        ('yellow', 'yellow card'),
       
    ]

class Event(models.Model):
    matche = models.ForeignKey(Match, related_name='events', on_delete=models.CASCADE)
    event_type = models.CharField(max_length=40,choices=EVENT_CHOICES,  default='None',blank=True, null=True)
    event_time = models.PositiveIntegerField(help_text='Time in minutes', default=0, blank=True, null=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='events_plyer', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.event_type} - {self.matche} - {self.event_time}'"

    


class League(models.Model):
    league_name = models.CharField(max_length=200, verbose_name='Name')
    info = models.CharField(max_length=254, verbose_name='Informations', blank=True)
    teams = models.ManyToManyField(Team, related_name='league_teams',blank=True)
    times = models.DateTimeField(auto_now_add=False, blank=True)
 
    def __str__(self):
        return self.league_name
    

class News(models.Model):   
    news_title = models.CharField(max_length=50,default="", verbose_name="Title")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news_author')
    news_content = models.TextField(verbose_name="Content")
    news_image = models.ImageField(upload_to='news_images', null=True, blank=True, verbose_name="Image")
    news_video = models.FileField(
        upload_to='news_videos', null=True, blank=True,

templates/FootBall/add_player.html
{% extends 'bases.html' %}
{% load static %}
{% load custom_tags %}
{% load crispy_forms_tags %}
{% block title %}ICFL  {% endblock title %}

{% block main-content %}

<!-- <div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}')";>
    <div class="container">
        <div class="row align-items-center">

            <div class="col-lg-12">

                <div class="col-lg-5 ml-auto">

                    <h2 class="text-white">Admin DashBoard</h2>
                    <p>To Control All The Information</p>

                </div>
            </div>

        </div>
    </div>
</div> -->




<!-- Display team  -->
<div class="site-section bg-light">
    <div class="container bg-light ">


        <div class="row">

            <div class="col-12 title-section mt-2">
                <a href="{% url 'FootBall:admin_dash' %}" class="heading">Admin Dashboard</a>
            </div>




            <div class="navbar col-md-12  d-flex justify-content-center mb-4 bg-dark ">


              
                <a href="{% url 'FootBall:admin_dash' %}" class="m-3 "> <span>Dashboard</span> </a>
                <a href="{% url 'FootBall:player_list' %}" class="m-3 "> <span>Player</span> </a>
                <a href="" class="m-3 "> <span>News</span> </a>



            </div>

            <div class="container-fluid ">


                <div class="row clearfix">
                    <div class="col-lg-12  ">
                        <div class="">
                            <div class="card-body">
                                <div class="header text-center bg-light">
                                    <h2>Add Player</h2>
                                </div>


                             
                                <div class="widget-next-match">
                                <div class="col-sm-8 offset-sm-1">
                                    <form action="" method="POST" enctype="multipart/form-data">

                                        
                                        {% csrf_token %}
                                        {{ form | crispy }}

                                        <button data-mdb-button-init type="submit" value="Submit" data-mdb-ripple-init
                                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Add Player</button>


                                    </form>
                                </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>













        </div>
    </div>
</div>


{% endblock main-content %}

templates/FootBall/add_player_team.html
{% extends 'bases.html' %}
{% load static %}
{% load custom_tags %}
{% load crispy_forms_tags %}
{% block title %} ICFL add player {% endblock title %}

{% block main-content %}


<div class="site-section bg-light">
    <div class="container bg-light ">


        <div class="row">

            <div class="col-12 title-section mt-2">
                <a href="{% url 'FootBall:user_dashboard' %}" class="heading">User Dashboard</a>


            </div>




            <div class="navbar col-md-12  d-flex justify-content-center mb-4 bg-dark ">


                
                <p  class="m-3 "> <span>Add New Player</span> </p>




            </div>





            <div class="container-fluid ">
                <div class="clearfix d-flex m-3 p-2 justify-content-center ">







                </div>




                <div class="row clearfix">
                    <div class="col-lg-6">
                        <div class="">
                            <div class="card-body ">
                                <div class="header text-center bg-light">

                                </div>

                        

                              
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ player_form| crispy  }}
                                    <button type="submit">Add Player</button>
                                </form>
                        
                            </div>
                        </div>
                    </div>
  



                </div>
            </div>













        </div>
    </div>
</div>


{% endblock main-content %}

templates/FootBall/news_list.html
{% extends 'bases.html' %}
{% load static %}
{% load custom_tags %}
{% block title %} ICFL {% endblock title %}

{% block main-content %}

<!-- <div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">
    <div class="container">
        <div class="row align-items-center">

            <div class="col-lg-12">

                <div class="col-lg-5 ml-auto">

                    <h2 class="text-white">Admin DashBoard</h2>
                    <p></p>          

                </div>
            </div>
        </div>
    </div>
</div> -->




<!-- Display team  -->
<div class="site-section bg-light">
    <div class="container bg-light ">


        <div class="row">

            <div class="col-12 title-section mt-2">
                <a href="{% url 'FootBall:admin_dash' %}" class="heading">Admin Dashboard</a>
            </div>




            <div class="navbar col-md-12  d-flex justify-content-center mb-4 bg-dark ">



                <a href="{% url 'FootBall:admin_dash' %}" class="m-3 "> <span>Dashboard</span> </a>
                <a href="{% url 'FootBall:add_news' %}" class="m-3 "> <span>Add News</span> </a>
                <a href="" class="m-3 "> <span>League</span> </a>






            </div>

            <div class="container-fluid ">


                <div class="row clearfix">
                    <div class="col-lg-12  ">
                        <div class="">
                            <div class="card-body">
                                <div class="header text-center bg-light">
                                </div>

                                {% for blog in news %}

                                <h3>{{ blog.news_title }}</h3>
                                <h6> <i> {{ blog.publish_date }} </i></h6>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <img src="/media/{{blog.news_image}}" alt="{{blog.news_image}}"
                                            title="{{blog.blog_title}}" width="100%">

                                    </div>

                                    <div class="col-sm-8">
                                        <p>{{blog.news_content }} <a
                                                href=" ">Read More</a>
                                        </p>
                                        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
                                        <a href="{% url 'FootBall:update_news' pk=blog.pk %}" class="btn btn-info btn-sm">Update</a>
                                        <a href="{% url 'FootBall:delete_news' del_id=blog.id %}" class="btn btn-danger btn-sm">Delete</a>

                                    </div>
                                </div>
                                {% endfor %}
                                <hr>




                            </div>
                        </div>
                    </div>
                </div>
            </div>













        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        $(".fordel").click(function (e) {
            e.preventDefault();
            // Hide all sections
            $(".section").addClass("d-none");
            // Show the target section
            var target = $(this).data("target");
            $(target).removeClass("d-none");
        });
    });
</script>

{% endblock main-content %}

templates/FootBall/referee.html
{% extends 'bases.html' %}
{% load static %}
{% load custom_tags %}
{% block title %} ICFL {% endblock title %}

{% block main-content %}

<!-- <div class="hero overlay" style="background-image: url('{% static 'imagess/bg_1.jpg' %}');">
    <div class="container">
        <div class="row align-items-center">

            <div class="col-lg-12">

                <div class="col-lg-5 ml-auto">

                    <h2 class="text-white">Admin DashBoard</h2>
                    <p></p>          

                </div>
            </div>
        </div>
    </div>
</div> -->




<!-- Display team  -->
<div class="site-section bg-light">
    <div class="container bg-light ">


        <div class="row">

            <div class="col-12 title-section mt-2">
                <a href="{% url 'FootBall:admin_dash' %}" class="heading">Admin Dashboard</a>
            </div>




            <div class="navbar col-md-12  d-flex justify-content-center mb-4 bg-dark ">


               
    
                <a href="{% url 'FootBall:admin_dash' %}" class="m-3 "> <span>Dashboard</span> </a>
                <a href="{% url 'FootBall:add_refeere' %}" class="m-3 ">Add Referee </a>
              
                <a href="" class="m-3 "> <span>News</span> </a>




            </div>

            <div class="container-fluid ">
               

                <div class="row clearfix">
                    <div class="col-lg-12  ">
                        <div class="">
                            <div class="card-body">
                                <div class="header text-center bg-light">
                                   
                                </div>


                                <div class="widget-next-match">
                                    <table class="table custom-table" >
                                        <thead>
                                            <tr>
                                                <th>SL</th>
                                                <th>Name</th>
                                                <th>Phone</th>
                                                <th>Email</th>
                                                <th>info</th>
                                                <th>Matche Ofcd</th>
                                                <th>referee_img</th>
                                                <th>Action</th>

                                               


                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for p in refeere %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td><strong class="text-white"> <a href="" class="text-white"> {{ p.referee_name }}</a> </strong></td>
                                                <td>{{ p.phone }}</td>
                                                <td>{{ p.email }}</td>
                                                <td>{{ p.info }}</td>
                                                <td >{{ p.total_officiated }}</td>
                                             
                                                <td>
                                                    <img src="{{p.referee_img.url }}" alt="" height="30px" width="30px">
                                                </td>
                                                <td >
                                                    <a href="{% url 'FootBall:update_refeere' p.pk %}" class="btn btn-info btn-sm">Update</a>
                                                    <a href="{% url 'FootBall:delete_refeere' del_id=p.id  %}" class="btn btn-primary btn-sm">Delete</a>

                                                </td>

                                               
                                                

                                        
                                    
                                               

                                            </tr>
                                            {% endfor %}
                                         

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>













        </div>
    </div>
</div>





{% endblock main-content %}

templates/FootBall/team_purchase.html
{% extends 'bases.html' %}
{% load static %}
{% load custom_tags %}
{% block title %} ICFL {% endblock title %}

{% block main-content %}






<!-- Display team  -->
<div class="site-section bg-light">
    <div class="container bg-light ">


        <div class="row">

            <div class="col-12 title-section mt-2">
                <a href="{% url 'FootBall:admin_dash' %}" class="heading">Admin Dashboard</a>
            </div>




            <div class="navbar col-md-12  d-flex justify-content-center mb-4 bg-dark ">


              
                <a href="{% url 'FootBall:admin_dash' %}" class="m-3 "> <span>Dashboard</span> </a>
                <a href="{% url 'FootBall:payment_details' %}" class="m-3 "> <span>Payment Details</span> </a>
                
        
            </div>

            <div class="container-fluid ">
               

                <div class="row clearfix">
                    <div class="col-lg-12  ">
                        <div class="">
                            <div class="card-body">
                                <div class="header text-center bg-light">
                                </div>


                                <div class="widget-next-match">
                                    <table class="table custom-table">
                                        <thead>
                                            <tr>
                                                <th>SL</th>
                                                <th>Team</th>
                                                <th>buyer</th>
                                                <th>purchase_date</th>
                                                <th>status</th>
                                                <th>Action</th>

                                                


        
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for team in team_purchase %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td><strong class="text-white">{{ team.teamname }}</strong></td>
                                                <td>{{ team.buyer }}</td>
                                                <td>{{ team.purchase_date }}</td>
                                                <td>{{ team.status }}</td>
                                              
       
                                                <td>
                                                    <a href="{% url 'FootBall:update_team_purchase' pk=team.pk %}" class="btn btn-info btn-sm">Upadte</a>
                                          
                                                    <a href="{% url 'FootBall:delete_team_purchase' del_id=team.id %}"  class="btn btn-primary btn-sm ">Delete </a>
                                                    <!-- data-target="#delteam"  -->

                                             



                                                </td>

                                                


                                            </tr>
                                            {% endfor %}
                                         

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>













        </div>
    </div>
</div>




{% endblock main-content %}