FootBall/urls.py
from django.urls import path
from FootBall import views

app_name = 'FootBall'

urlpatterns = [

    path("", views.Home, name="home"),
     
    #  for team buy 
    path('team-list/', views.team_list, name ="team_list"),
    path('teams/buy/<int:team_id>/', views.buy_team, name='buy_team'),

    # User dashboard 
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('purchased-team/', views.purchased_team_info_view, name='purchased_team_info'),
    path('invoice/<int:purchase_id>/', views.invoice_view, name='invoice_view'),
    path('update-team-user/<pk>/', views.UpdateTeam_user, name='update_team_user'),

    path('player-team/', views.player_team_info_view, name='player_team_info'),
    path('add-player-team/', views.add_player_team, name='add_player_team'),
    path('team-player-info/<int:player_id>/', views.team_playerinfo, name='team_player_info'),

    path('team-matche-info/', views.team_matche_info, name='team_matche_info'),

    path('team-report-user/', views.teamreport_user, name='team_report_user'),
    path('team-report-info-user/<int:team_id>/', views.team_report_info_view_user, name='team_report_info_user'),




    
    #  admin dashbord CRUD for team
    path('admin-dashboard/', views.admin_dashboard, name='admin_dash'),
    path('admin-team-list/', views.adminteam, name='admin_team'),
    path('add-team/', views.add_team, name='add_team'),
    path('update-team/<pk>/', views.UpdateTeam, name='update_team'),
    path('delete-team/<int:del_id>/', views.DeleteTeam, name='delete_team'),


    #  admin dashbord CRUD for player
    path('player-list/', views.Player_list.as_view(), name='player_list'),
    path('player-info/<int:player_id>/', views.playerinfo, name='player_info'),
    path('add-player/', views.add_player, name='add_player'),
    path('update-player/<pk>/', views.UpdatePlayer, name='update_player'),
    path('delete-player/<int:del_id>/', views.Deleteplayer, name='delete_player'),

    #  admin dashbord CRUD for Matches
    path('matches-list/', views.matchelist, name='matches_list'),
    path('create-matche/', views.create_match, name='create_matche'),
    path('update-matche/<pk>/', views.update_match.as_view(), name='update_matche'),


    #admin dashbord CURD for Refeere
    path('referee/',views.refeere, name='referee' ),
    path('add-refeere/', views.add_refeere, name='add_refeere'),
    path('update-refeere/<pk>/', views.UpdateReferee, name='update_refeere'),
    path('delete-refeere/<int:del_id>/', views.DeleteRefee, name='delete_refeere'),


    # admin dashboard CURD for News 
    path('news-list', views.newslist, name='news_list'),
    path('add-news/', views.add_News, name='add_news'),

    path('update-news/<pk>/', views.UpdateNews, name='update_news'),
    path('delete-news/<int:del_id>/', views.DeleteNews, name='delete_news'),


    # admin dashboard CURD for League
    path('league-list', views.leaguelist, name='league_list'),
    path('add-league/', views.add_league, name='add_league'),
    path('update-league/<pk>/', views.Updateleague, name='update_league'),
    path('delete-league/<int:del_id>/', views.Deleteleague, name='delete_league'),

    # admin dashboard CURD for team puchase  
    path('team-purchase/', views.teampurchase, name='team_purchase'),
    path('payment-details/', views.Paymentdetails, name='payment_details'),
    path('update-team-purchase/<pk>/', views.UpdateteamPur, name='update_team_purchase'),
    path('delete-team-purchase/<int:del_id>/', views.DeleteTeamPurchase, name='delete_team_purchase'),


    # admin dashboard CURD for team report 
    path('team-report/', views.teamreport, name='team_report'),
    path('team-report-info/<int:team_id>/', views.team_report_info_view, name='team_report_info'),



     # admin dashboard CURD for matche report 
    path('matche-report/', views.Matchereport, name='matche_report'),










   










   



    path('players/', views.players, name="players"),
    path('blogs/', views.blogs, name="blogs"),
    path('contact/', views.contact, name="contact"),
    path('single-players/', views.single_players, name="single_ply"),

    # for show live matches and information 
    path('live-matches/', views.livematch, name="live_matches"),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/',views.MatcheInfo,name='match_info'),
    path('match-info/<int:match_id>/<int:team1_id>/<int:team2_id>/', views.MatcheInfo, name='match_detail'),


   






]

ICFL/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("league/", include('FootBall.urls')),
    path("login/", include('Login.urls')),
    path("", views.index, name='index'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'Login'

urlpatterns = [

    path('signup/', views.sign_up, name='signup'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('profile/', views.profile, name='profile'),

    # path('change-profile/', views.user_change, name='user_change'),
    # path('update_password/', views.update_password, name='update_password'), 
    path('add_propic/', views.add_propic, name='add_propic'),  
    path('change_propic/', views.change_propic, name='change_propic'),     


]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



  {% comment %} new copy {% endcomment %}

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
    integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
    crossorigin="anonymous" />

  <link rel="stylesheet" href="{% static 'css/styles.css'  %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">


  <!-- navbar  -->
  <script scr="https://fonts.googleapis.com/icon?family=Material+Icons"> </script>

  <script scr="https://fonts.googleapis.com/css?family=Montserrat"> </script>


  <title>{% block title %} Hassan {% endblock title %} </title>



</head>

<body>

  <navbar>
   
     


    <div class="navbar1">
      <div class="navbar-body">
        <li class="active">
          <a href="#" class="item">TICKETS</a>
        </li>
        <li><a href="#" class="item">IUBAT LEAUGE+</a></li>
        <li><a href="#" class="item">IUBAT STORE</a></li>
        <li><a href="#" class="item">INSIDE IUBAT</a></li>
      </div>

      <div class="line"></div>

      <div class="navbar-double">

        <div class="navbar-body2">
          <li class="dropdown">
            <a class="items" href="{% url 'FootBall:home' %}">TOURNAMENTS</a>
            <div class="dropdown-content">
              <a class="dropitem" href="#">IUBAT FootBall League</a>
              <a class="dropitem" href="#">IUBAT Cricket League</a>
              <a class="dropitem" href="#">IUBAT BasketBall League</a>
            </div>
          </li>

          <li><a href="{% url 'FootBall:matches' %}" class="items">MATCH LIVE</a></li>
          <li><a href="#" class="items">NEWS</a></li>
          <li><a href="#" class="items">WATCH ON IUBAT+</a></li>
          <li><a href="#" class="items">PLAY</a></li>
          <li><a href="#" class="items">SHOP</a></li>

          
        </div>


       

        <div class="navbar-body3">
          
          <div class="dropdowns">
            {% if user.user_profile %}
           <img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle"  height="30px"> </a>
            {% else %}
             <img src="{% static 'Images/logo.2.png' %}"class="rounded-circle" height="30px"> </a>
            {% endif %}
    
            <div class="dropdown-contents">
              {% if user.is_authenticated %}
              <a class="userdropitem" href="{% url 'Login:profile' %}">Profile</a>
              <a class="userdropitem" href="{% url 'Login:logout' %}">Logout</a>
              {% else %}
              <a class="userdropitem" href="{% url 'Login:signup' %}">Sign Up</a>
              <a class="userdropitem" href="{% url 'Login:login' %}">Login</a>
             
              {% endif %}
            
            </div>
          
          </div>
        </div>

      </div>


      <div class="search">
        <div>
          <input type="text" placeholder="Search . . ." required>
        </div>
     </div>


     


     









    </div>
  </navbar>


  {% block main-content %}




  {% endblock main-content %}


  <!-- Start Footer -->
  <!-- {% comment %}  -->


  <!-- {% endcomment %} -->
  <!-- End Footer -->


  <!-- Bootstrap JS and dependencies -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script> -->
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script> -->
  <!-- <script src="{% static 'js/index.js' %}"></script> -->

</body>

</html>

templates/bases.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- <title>Soccer &mdash; Website by Colorlib</title> -->
  <title>{% block title %} ICFL {% endblock title %} </title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %} ">

  <link rel="stylesheet" href="{% static 'css/mystyle.css' %} ">
  






      <!-- Latest compiled and minified CSS -->
      <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.0.1/dist/css/bootstrap.min.css"> -->
  
      <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- jQuery Countdown Plugin -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-countdown/2.2.0/jquery.countdown.min.js"></script> -->


<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>



</head>

<body>
  

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>


    <header class="site-navbar py-4" role="banner">

      <div class="container">
        <div class="d-flex align-items-center">
          <div class="site-logo">
            <a href="{% url 'FootBall:home' %}">
              <h1>ICFL</h1>
              <!-- <img src="{% static  'imagess/logo.png' %}" alt="Logo"> -->
            </a>
          </div>
          <div class="ml-auto">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class=" navbar-nav site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                <li class="nav-item"><a href="{% url 'FootBall:home' %}" class="nav-link">Home</a></li>
              
                <li class="nav-item"><a href="{% url 'FootBall:live_matches'  %}" class="nav-link">Matche Live</a></li>
           
                <li class="nav-item"><a href="{% url 'FootBall:players' %}" class="nav-link">Players</a></li>
                <li class="nav-item"><a href="{% url 'FootBall:blogs' %}" class="nav-link">News</a></li>
                <li class="nav-item"><a href="{% url 'FootBall:contact' %}" class="nav-link">Contact</a></li>

                <!-- <li class="navbar-body3"> -->
                  <li class="dropdowns">
                    {% if user.users %}
                   <img src="/media/{{user.users.pro_pic}}" class="rounded-circle"  height="30px" width="30px"> </a>
                    {% else %}
                     <img src="{% static 'Images/logo.2.png' %}"class="rounded-circle" height="30px" width="30px"> </a>
                    {% endif %}
            
                    <div class="dropdown-contents">
                      {% if user.is_authenticated %}

                      {% if  request.user.username == 'admin' %}

                      <a class="userdropitem" href="{% url 'FootBall:admin_dash' %}">Admin DB</a>
                      <a class="userdropitem" href="{% url 'Login:logout' %}">Logout</a>

                      {% else %}
                      <a class="userdropitem" href="{% url 'Login:profile' %}">Profile</a>
                      <a class="userdropitem" href="{% url 'Login:logout' %}">Logout</a>
                      {% endif %}
                      {% else %}
                      <a class="userdropitem" href="{% url 'Login:signup' %}">Sign Up</a>
                      <a class="userdropitem" href="{% url 'Login:login' %}">Login</a>
                     
                      {% endif %}
                    
                    </div>
                  
                  </div>
                <!-- </li> -->
              </ul>
            </nav>

            <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right text-white"><span
                class="icon-menu h3 text-white"></span></a>
          </div>
        </div>
      </div>

    </header>
    

<script>
      document.addEventListener('DOMContentLoaded', function () {
  const navLinks = document.querySelectorAll('.navbar-nav .nav-link');

  navLinks.forEach(link => {
    link.addEventListener('click', function () {
      // Remove active class from all links
      navLinks.forEach(nav => nav.parentElement.classList.remove('active'));
      
      // Add active class to the clicked link's parent
      this.parentElement.classList.add('active');
      
      // Optionally, change color (you can also do this via CSS)
      navLinks.forEach(nav => nav.style.color = '#333'); // Reset color
      this.style.color = '#ff002b'; // Change color for active link
    });
  });
});
</script>
 

    {% block main-content %}


    



   {% endblock main-content %}

    <footer class="footer-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>News</h3>
              <ul class="list-unstyled links">
                <li><a href="#">All</a></li>
                <li><a href="#">Club News</a></li>
                <li><a href="#">Media Center</a></li>
                <li><a href="#">Video</a></li>
                <li><a href="#">RSS</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Tickets</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Online Ticket</a></li>
                <li><a href="#">Payment and Prices</a></li>
                <li><a href="#">Contact &amp; Booking</a></li>
                <li><a href="#">Tickets</a></li>
                <li><a href="#">Coupon</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Matches</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Standings</a></li>
                <li><a href="#">World Cup</a></li>
                <li><a href="#">La Lega</a></li>
                <li><a href="#">Hyper Cup</a></li>
                <li><a href="#">World League</a></li>
              </ul>
            </div>
          </div>

          <div class="col-lg-3">
            <div class="widget mb-3">
              <h3>Social</h3>
              <ul class="list-unstyled links">
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Instagram</a></li>
                <li><a href="#">Youtube</a></li>
              </ul>
            </div>
          </div>

        </div>

        <div class="row text-center">
          <div class="col-md-12">
            <div class=" pt-5">
              <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script> All rights reserved | ICFL  <i class="icon-heart"
                  aria-hidden="true"></i> by <a href="" class="" target="_blank">Hassan_Murad</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>

        </div>
      </div>
    </footer>



  </div>
  <!-- .site-wrap -->

  <script src="{% static '.js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static '.js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static '.js/jquery-ui.js' %}"></script>
  <script src="{% static '.js/popper.min.js' %}"></script>
  <script src="{% static '.js/bootstrap.min.js' %}"></script>
  <script src="{% static '.js/owl.carousel.min.js' %}"></script>
  <script src="{% static '.js/jquery.stellar.min.js' %}"></script>
  <script src="{% static '.js/jquery.countdown.min.js' %}"></script>
  <script src="{% static '.js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static '.js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static '.js/aos.js' %}"></script>
  <script src="{% static '.js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static '.js/jquery.sticky.js' %}"></script>
  <script src="{% static '.js/jquery.mb.YTPlayer.min.js' %}"></script>



  <script src="{% static '.js/main.js' %}"></script>



 
</body>

</html>